services:
  postgres:
    image: postgres:15
    container_name: usertask-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: usertaskdb
    ports:
      - "5432:5432"
